client_config_backend: settings
client_config:
  client_id: 337388461042-rtmgaotjriaikhuk3veqvdajvuvnfm3u.apps.googleusercontent.com
  client_secret: DcdErRIoEWjVHcCKEpfKLbPz

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install